language: node_js
sudo: false

node_js:
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '10.0'
  - '10.1'
  - '10.2'
  - '10.3'
  - '10.4'
  - '10.5'
  - '10.6'
  - '10.7'
  - '10.8'
  - 'node'

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

cache:
  directories:
    - node_modules
